### ISSUE TITLE
Laravel 5?

### ISSUE THREAD

**Issue by sixty8** [madcoda/php-youtube-api#28]
Laravel 5 support?

**Comment by madcoda** [comment]
I've just started studying L5, any thoughts and ideas? (Though this package does not depend on laravel now)

**Comment by andrewcaulfield** [comment]
Would love to see upload to YouTube supported in the package.

**Comment by tplaner** [comment]
This package works out of the box with Laravel 5. No changes are needed.

**Comment by sixty8** [comment]
+1

**Comment by kalimba** [comment]
Hi,

In order to use the package in Laravel 5 (or Laravel 4, but i didn't test) as facade or IOC you just need really simple two files.

* Create a folder which is called `YotutubeDataApi`  inside `app/Providers`

* Create a service provider (`app/Providers/YoutubeDataApi/YoutubeDataApiProvider.php`) to register `madcoda/php-youtube-api`.

        <?php

        namespace App\Providers\YoutubeDataApi;

        use Illuminate\Foundation\AliasLoader;
        use Illuminate\Support\ServiceProvider;
        use Madcoda\Youtube;

        class YoutubeDataApiProvider extends ServiceProvider
        {
            /**
             * Bootstrap the application services.
             *
             * @return void
             */
            public function boot()
            {
               AliasLoader::getInstance()->alias(
                    'Youtube',
                    'App\Providers\YoutubeDataApi\YoutubeDataApiFacades'
                );
            }

            /**
             * Register the application services.
             *
             * @return void
             */
            public function register()
            {
                $this->app->singleton('Youtube', function()
                {
                    return new Youtube(['key' => config('services.youtubekey')]);
                });
            }
        }

	> Note: You need to add your key to `app/config/services.php`

		[
        	...,
    		'youtubekey' => 'Your Key'
        ]


* Create a facade file (`app/Providers/YoutubeDataApi/YoutubeDataApiFacades.php`)  if you want to use without IOC

        <?php

        namespace App\Providers\YoutubeDataApi;

        use Illuminate\Support\Facades\Facade;

        class YoutubeDataApiFacades extends Facade
        {
            /**
             * The name of the binding in the IoC container.
             *
             * @return string
             */
            protected static function getFacadeAccessor()
            {
                return 'Youtube';
            }
        }


Now open up app/config/app.php and add the service provider to your providers array.

    'providers' => [
        ...,
        App\Providers\YoutubeDataApi\YoutubeDataApiProvider::class,
    ]


**Example:**

With IOC: `app('Youtube')->getVideoInfo('YOUTUBEID')`
As Facade: `\Youtube::getVideoInfo('c_VPZosKrFM')`

**Comment by madcoda** [comment]
Laravel 5 is supported, please read this [Getting Started with Laravel 5](https://github.com/madcoda/php-youtube-api/wiki/started-with-laravel-5)
